
// Heroes
export const HEROES_FETCHING = 'HEROES_FETCHING';
export const HEROES_FETCHED = "HEROES_FETCHED";
export const HEROES_FETCHING_ERROR = "HEROES_FETCHING_ERROR"
export const HERO_DELETE = "HERO_DELETE";
export const HERO_CREATE = "HERO_CREATE";


// Filters
export const FILTERS_FETCHING = "FILTERS_FETCHING";
export const FILTERS_FETCHED = "FILTERS_FETCHED";
export const FILTERS_FETCHING_ERROR = "FILTERS_FETCHING_ERROR";
export const ACTIVE_FILTER_CHANGED = "ACTIVE_FILTER_CHANGED";